# Generated by Django 6.0 on 2026-01-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_freemealvoucher_loyaltyaccount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loyaltyaccount",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="confirmed_at",
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="FreeMealVoucher",
        ),
        migrations.DeleteModel(
            name="LoyaltyAccount",
        ),
    ]
