# Generated by Django 6.0 on 2026-01-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0003_remove_loyaltyaccount_user_remove_order_confirmed_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant_code",
            field=models.CharField(default="standard", max_length=20),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
