# Generated by Django 6.0 on 2026-01-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderitem_variant_code_alter_orderitem_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address_detail",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
