# Generated by Django 6.0 on 2026-01-10 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="referral",
            name="no_self_referral",
        ),
        migrations.RemoveField(
            model_name="referralcode",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="rewardledger",
            name="marketing_r_user_id_f80afe_idx",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="non_cumulable",
        ),
        migrations.RemoveField(
            model_name="promotionredemption",
            name="device_id",
        ),
        migrations.RemoveField(
            model_name="promotionredemption",
            name="ip_hash",
        ),
        migrations.AlterField(
            model_name="freeitemvoucher",
            name="max_item_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("2000.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="promo_type",
            field=models.CharField(
                choices=[("PERCENT", "Percent"), ("FIXED_AMOUNT", "Fixed amount")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="promotionredemption",
            name="status",
            field=models.CharField(
                choices=[("APPLIED", "Applied"), ("CANCELLED", "Cancelled")],
                default="APPLIED",
                max_length=12,
            ),
        ),
        migrations.RemoveField(
            model_name="referral",
            name="qualified_order",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="referral_code",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="referred",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="referrer",
        ),
        migrations.RemoveField(
            model_name="rewardledger",
            name="user",
        ),
        migrations.DeleteModel(
            name="ReferralCode",
        ),
        migrations.DeleteModel(
            name="Referral",
        ),
        migrations.DeleteModel(
            name="RewardLedger",
        ),
    ]
