# Generated by Django 6.0 on 2026-01-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_remove_referral_no_self_referral_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freeitemvoucher",
            name="max_item_value",
        ),
        migrations.RemoveField(
            model_name="loyaltyaccount",
            name="stamps",
        ),
        migrations.AddField(
            model_name="freeitemvoucher",
            name="tier_value",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name="loyaltyaccount",
            name="count_1000",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loyaltyaccount",
            name="count_1500",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loyaltyaccount",
            name="count_500",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
