# Generated by Django 6.0 on 2026-01-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="available_weekdays",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="meal",
            name="max_per_order",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="meal",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
