# Generated by Django 6.0 on 2026-01-12 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_meal_available_weekdays_meal_max_per_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="price",
        ),
        migrations.CreateModel(
            name="MealVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="shop.meal",
                    ),
                ),
            ],
            options={
                "unique_together": {("meal", "code")},
            },
        ),
    ]
